[package]
name = "voker"
version = "0.1.0"
edition = "2021"

[dependencies]
comfy = { git = "https://codeberg.org/twink/comfy", rev = "83186a54ef5b7a308914bad66374b0e91ddd5887" }
twink = { version = "1.1.3", features = ["12-hour", "log"] }
